name: caller-workflow
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
  call-workflow:
    needs: test
    uses: ./.github/workflows/reusable-workflow.yaml
    with:
      myInput: "Hello, world!"
  print-output:
    needs: call-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Get output value
        run: echo "Output value is ${{ needs.call-workflow.outputs.myOutput }}"