name: Deploy Project  # Name of the workflow
on: [push, workflow_dispatch]  # Trigger workflow on push or manual dispatch
jobs:
  test:  # Define the test job
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    steps:
      - name: Get code  # Step to check out the repository code
        uses: actions/checkout@v3
      - name: Install NodeJS  # Step to set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify Node.js version 18
      - name: Install dependencies  # Step to install project dependencies
        run: npm ci
      - name: Run tests  # Step to run tests
        run: npm test

  # Deploy job runs after the test job, regardless of test job success or failure
  deploy:
    if: always()  # Ensure this job runs even if the test job fails
    needs: test  # This job depends on the completion of the test job
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    steps:
      - name: Get code  # Step to check out the repository code
        uses: actions/checkout@v3
      - name: Install NodeJS  # Step to set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify Node.js version 18
      - name: Install dependencies  # Step to install project dependencies
        run: npm ci
      - name: Build project  # Step to build the project
        run: npm run build
      - name: Deploy  # Step to deploy the project
        run: echo "Deploying ..."  # Replace this with actual deployment commands