name: matrix practice
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14, 15, 16]
        include:
        - os: ubuntu-latest
          node-version: 18
        exclude:
        - os: windows-latest
          node-version: 14
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}