name: Expression output
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'
  workflow_dispatch:
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get output
        run: echo "The output is ${{ toJson(github) }}"