name: reusable-workflow
on:
  workflow_call:
    inputs:
      myInput:
        required: true
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: display input
        run: echo ${{ inputs.myInput }}