name: Run ID
on:
  workflow_dispatch:
jobs:
  runid:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Run ID
        run: echo "Run ID :$GITHUB_RUN_ID"
      - name: Run number
        run: echo "Run ID :$GITHUB_RUN_NUMBER"